name: linter
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  formater:
    name: Python Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Cut sha for PR branch name
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | cut -c 1-6)" >> $GITHUB_ENV
          echo ${{ env.GITHUB_SHA_SHORT }}
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'
      - run: pip install yapf
        shell: bash
      - name: run yapf
        id: yapf
        shell: bash
        run: |
          is_formatted=0
          yapf  . --verbose --recursive --diff --parallel > /dev/null || is_formatted=1
          yapf  . --verbose --recursive --in-place --parallel > /dev/null
          echo "IS_FORMATTED=$is_formatted" >> $GITHUB_ENV
          echo "is_formatted:  ${{ env.IS_FORMATTED  }}"
      - name: yapf exit failure
        if: ${{ env.IS_FORMATTED != 0 }}
        run: exit 1
        shell: bash
